name: Grype SCA

on:
    push:
        branches: [ "workflows" ]
    schedule:
        - cron: 0 12 * * 1
    # At 12:00 on Monday.
jobs:
    Scan:
    # Importing a reusable workflow from another repository and branch
        uses: t-kolev/ric-plt-xapp-frame/.github/workflows/grype.yml@master