name: Snyk SCA

on:
    push:
        branches: [ "workflows" ]
    schedule:
        - cron: 0 12 * * 1
    # At 12:00 on Monday.
    
jobs:
    Scan:
    # Importing a reusable workflow from another repository and branch
        uses: t-kolev/Continuous-SCA-Scanning/.github/workflows/snyk.yaml@main
        secrets:
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}