name: Trivy SCA

on:
  push:
    branches: [ "workflows" ]
    
jobs:
    Scan:
    # Importing a reusable workflow from another repository and branch
<<<<<<< HEAD
     uses: t-kolev/ric-plt-xapp-frame/.github/workflows/trivy.yml@master
=======
     uses: t-kolev/ric-plt-xapp-frame/.github/workflows/trivy.yml@master 
>>>>>>> refs/remotes/origin/workflows
